INSERT INTO ability VALUES
(1,'Biotic Rifle','Ana’s rifle shoots darts that can restore health to her allies or deal ongoing damage to her enemies. She can use the rifle’s scope to zoom in on targets and make highly accurate shots.',false,1),
(2,'Sleep Dart','Ana fires a dart from her sidearm\, rendering an enemy unconscious (though any damage will rouse them).',false,1),
(3,'Biotic Grenade','Ana tosses a biotic bomb that deals damage to enemies and heals allies in a small area of effect. Affected allies briefly receive increased healing from all sources\, while enemies caught in the blast cannot be healed for a few moments.',false,1),
(4,'Nano Boost','After Ana hits one of her allies with a combat boost\, they temporarily move faster\, deal more damage\, and take less damage from enemies’ attacks.',true,1),
(5,'Configuration: Recon','In Recon mode\, Bastion is fully mobile\, outfitted with a submachine gun that fires steady bursts of bullets at medium range.',false,2),
(6,'Configuration: Sentry','In Sentry mode\, Bastion is a stationary powerhouse equipped with a gatling gun capable of unleashing a hail of bullets. The gun''s aim can be \''walked\'' across multiple targets dealing devastating damage at short to medium range.',false,2),
(7,'Reconfigure','Bastion transforms between its two primary combat modes to adapt to changing battlefield conditions.',false,2),
(8,'Self-Repair','Bastion restores its health; it cannot move or fire weapons while the repair process is in effect.',false,2),
(9,'Configuration: Tank','In Tank mode\, Bastion extends wheeled treads and a powerful long-range cannon. The cannon’s explosive shells demolish targets in a wide blast radius\, but Bastion can only remain in this mode for a limited time.',true,2),
(10,'Fusion Cannons','D.Va''s mech is equipped with twin short-range rotating cannons. They lay down continuous\, high-damage fire without needing to reload\, but slow D.Va’s movement while they’re active.',false,3),
(11,'Boosters','D.Va’s mech launches into the air\, her momentum carrying her forward. She can turn and change directions or barrel through her enemies\, knocking them back.',false,3),
(12,'Defense Matrix','D.Va can activate this forward-facing targeting array to shoot incoming projectiles out of the air.',false,3),
(13,'Eject','D.Va ejects out of her mech when it is destroyed.',false,3),
(14,'Self-Destruct','D.Va ejects from her mech and sets its reactor to explode\, dealing massive damage to nearby opponents.',true,3),
(15,'Light Gun','While outside of her mech\, D.Va can continue the fight with a mid-range automatic blaster.',false,3),
(16,'Call Mech','If her armored battle suit is destroyed\, D.Va can call down a fresh mech and return to the fray.',true,3),
(17,'Shuriken','Genji looses three deadly throwing stars in quick succession. Alternatively\, he can throw three shuriken in a wider spread.',false,4),
(18,'Swift Strike','Genji darts forward\, slashing with his katana and passing through foes in his path. If Genji eliminates a target\, he can instantly use this ability again.',false,4),
(19,'Deflect','With lightning-quick swipes of his sword\, Genji reflects any oncoming projectiles and can send them rebounding towards his enemies.',false,4),
(20,'Cyber-Agility','Thanks to his cybernetic abilities\, Genji can climb walls and perform jumps in mid-air.',false,4),
(21,'Dragonblade','Genji brandishes his katana for a brief period of time. Until he sheathes his sword\, Genji can deliver killing strikes to any targets within his reach.',true,4),
(22,'Storm Bow','Hanzo nocks and fires an arrow at his target.',false,5),
(23,'Scatter Arrow','Hanzo shoots a fragmenting arrow that ricochets off walls and objects and can strike multiple targets at once.',false,5),
(24,'Sonic Arrow','Hanzo launches an arrow that contains a sonar tracking device. Any enemy within its detection radius is visibly marked\, making them easier for Hanzo and his allies to hunt down.',false,5),
(25,'Wall Climb','Hanzo can climb any vertical surface.',false,5),
(26,'Dragonstrike','Hanzo summons a Spirit Dragon which travels through the air in a line. It passes through walls in its way\, devouring any enemies it encounters.',true,5),
(27,'Frag Launcher','Junkrat''s Frag Launcher lobs grenades a significant distance. They bounce to reach their destination\, and blow up when they strike an enemy.',false,6),
(28,'Concussion Mine','After placing one of his homemade Concussion Mines\, Junkrat can trigger it to damage enemies and send them flying... or propel himself through the air.',false,6),
(29,'Steel Trap','Junkrat tosses out a giant\, metal-toothed trap. Should an enemy wander too close to the trap\, it clamps on\, injuring and immobilizing them.',false,6),
(30,'Total Mayhem','Junkrat''s deranged sense of humor persists past his death. If killed\, he drops several live grenades.',false,6),
(31,'RIP-Tire','Junkrat revs up a motorized tire bomb and sends it rolling across the battlefield\, climbing over walls and obstacles. He can remotely detonate the RIP-Tire to deal serious damage to enemies caught within the blast\, or just wait for it to explode on its own.',true,6),
(32,'Sonic Amplifier','Lúcio can hit his enemies with sonic projectiles or knock them back with a blast of sound.',false,7),
(33,'Crossfade','Lúcio continuously energizes himself\, and nearby teammates\, with music. He can switch between two songs: one amplifies movement speed\, while the other regenerates health.',false,7),
(34,'Amp It Up','Lúcio increases the volume on his speakers\, boosting the effects of his songs.',false,7),
(35,'Wall Ride','Lúcio rides along a wall. This has a slight upwards angle\, allowing him to ascend the wall.',false,7),
(36,'Sound Barrier','Protective waves radiate out from Lúcio’s Sonic Amplifier\, briefly providing him and nearby allies with personal shields.',true,7),
(37,'Peacekeeper','McCree fires off a round from his trusty six-shooter. He can fan the Peacekeeper’s hammer to swiftly unload the entire cylinder.',false,8),
(38,'Combat Roll','McCree dives in the direction he''s moving\, effortlessly reloading his Peacekeeper in the process.',false,8),
(39,'Flashbang','McCree heaves a blinding grenade that explodes shortly after it leaves his hand. The blast staggers enemies in a small radius.',false,8),
(40,'Deadeye','Focus. Mark. Draw. McCree takes a few precious moments to aim; when he''s ready to fire\, he shoots every enemy in his line of sight. The weaker his targets are\, the faster he''ll line up a killshot.',true,8),
(41,'Endothermic Blaster','Mei''s blaster unleashes a concentrated\, short-range stream of frost that damages\, slows\, and ultimately freezes enemies in place. Mei can also use her blaster to shoot icicle-like projectiles at medium range.',false,9),
(42,'Cryo-Freeze','Mei instantly surrounds herself with a block of thick ice. She heals and ignores damage while encased\, but cannot move or use abilities.',false,9),
(43,'Ice Wall','Mei generates an enormous ice wall that obstructs lines of sight\, stops movement\, and blocks attacks.',false,9),
(44,'Blizzard','Mei deploys a weather-modification drone that emits gusts of wind and snow in a wide area. Enemies caught in the blizzard are slowed and take damage; those who linger too long are frozen solid.',true,9),
(45,'Caduceus Staff','Mercy engages one of two beams that connect to an ally. By maintaining the beams\, she can either restore that ally''s health or increase the amount of damage they deal.',false,10),
(46,'Caduceus Blaster','Mercy shoots a round from her sidearm. It''s best reserved for emergency personal defense.',false,10),
(47,'Guardian Angel','Mercy flies towards a targeted ally\, allowing her to reach them quickly and provide assistance in crucial moments.',false,10),
(48,'Angelic Descent','Propelled by her Valkyrie suit\, Mercy slows the speed of her descent from great heights.',false,10),
(49,'Resurrect','Mercy radiates restorative power\, bringing nearby dead allies back into the fight with full health.',true,10),
(50,'Rocket Launcher','Pharah’s primary weapon launches rockets that deal significant damage in a wide blast radius.',false,11);

INSERT INTO hero VALUES
(1,'Ana',200,0,0,'Ana Amari'),
(2,'Bastion',200,100,0,'sST Laboratories Siege Automaton E54'),
(3,'D.Va',200,400,0,'Hana Song'),
(4,'Genji',200,0,0,'Genji Shimada'),
(5,'Hanzo',200,0,0,'Hanzo Shimada'),
(6,'Junkrat',200,0,0,'Jamison Fawkes'),
(7,'Lúcio',200,0,0,'Lúcio Correia dos Santos'),
(8,'McCree',200,0,0,'Jesse McCree'),
(9,'Mei',250,0,0,'Mei-Link Zhou'),
(10,'Mercy',200,0,0,'Angela Ziegler'),
(11,'Pharah',200,0,0,'Fareeha Amari'),
(12,'Reaper',250,0,0,'Gabriel Reyes'),
(13,'Reinhardt',300,200,0,'Reinhardt Wilhelm'),
(14,'Roadhog',600,0,0,'Mako Rutledge'),
(15,'soldier: 76',200,0,0,'Jack Morrison'),
(16,'symmetra',100,0,0,'satya Vaswani'),
(17,'Torbjörn',200,0,0,'Torbjörn Lindholm'),
(18,'Tracer',150,0,0,'Lena Oxton'),
(19,'Widowmaker',200,0,0,'Amélie Lacroix'),
(20,'Winston',400,100,0,'Winston'),
(21,'Zarya',200,0,200,'Aleksandra Zaryanova'),
(22,'Zenyatta',50,0,150,'Tekhartha Zenyatta'),
(23,'sombra',200,0,0,'░░░░░░'),
(24,'Orisa',200,200,0,'Orisa');

